# -*- coding: utf-8 -*-
"""aula_detestavel_back_end_ana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Tkm7iyjHHj3kp9Cz56p5JDr6LdfL9oR
"""

import mongomock
from pymongo.errors import PyMongoError

print("INICIANDO O LABORATÓRIO PRÁTICO DE BACK-END")

cliente = mongomock.MongoClient()
db = cliente['loja_banco']
produtos = db['produtos']

print("[CONEXÃO]: Simulador do MongoDB iniciado com sucesso!")

novo_item = {
    "nome": "Teclado Mecânico Gamer",
    "preço": 189.90,
    "estoque":25
}

retorno = produtos.insert_one(novo_item)

print(f"[CREATE]: Item salvo! O banco carimbou o ID único: {retorno.inserted_id}")

print("\n--- [READ]: CONSULTANDO OS ITENS DA GAVETA ---")

todos_produtos = produtos.find()

for p in todos_produtos:
  print(f"Produto: {p['nome']} | Preço: R$ {p['preço']} | Estoque:{p['estoque']}")


filtro_busca = {"nome": "Teclado Mecânico Gamer"}
nova_informacao = {"$set": {"preço": 219.90}}

produtos.update_one(filtro_busca, nova_informacao)
print("\n [UPDATE]: O preço do Teclado foi reajustado no banco!")

produto_conferido = produtos.find_one(filtro_busca)
print(f" [CONFERÊNCIA]: Novo preço verificado no banco: R$ {produto_conferido['preço']}")
print("\n- [OTIMIZAÇÃO]: indice de precos criados! consultas agora são instantâneas.")

# ---------------------------------------------------------------------
# 🔒 BLOCO 6: TRANSAÇÃO (O Botão de Segurança "Tudo ou Nada")
# ---------------------------------------------------------------------
print("\n🔒 [TRANSAÇÃO]: Iniciando uma simulação de venda segura...")

# Adicionando um mouse rapidamente para testar a venda
produtos.insert_one({"nome": "Mouse Sem Fio", "preco": 50.0, "estoque": 5})

# Abrindo uma sessão trancada com o banco
# A biblioteca mongomock não suporta sessões, então este bloco será comentado
# with cliente.start_session() as sessao:
#     with sessao.start_transaction():

#         # Passo 1: Diminuir 1 unidade do estoque do Mouse
#         produtos.update_one({"nome": "Mouse Sem Fio"}, {"$inc": {"estoque": -1}}, session=sessao)

#         # Passo 2: Criar a nota fiscal/recibo na coleção 'vendas'
#         db['vendas'].insert_one({"item": "Mouse Sem Fio", "qtd": 1, "status": "Pago"}, session=sessao)

#         print("🎉 [TRANSAÇÃO]: Sucesso! Estoque reduzido e recibo gerado juntos.")

print("⚠️ [AVISO]: O BLOCO DE TRANSAÇÃO foi pulado, pois mongomock não suporta sessões.\nPara usar transações, é necessário um servidor MongoDB real.")

print("\n=======================================================")
print("🏁 FIM DO LABORATÓRIO: TODOS OS BLOCOS FUNCIONANDO!")
print("=======================================================")